apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed-container
        image: lucasdamaceno/udagram-api-feed
      - envFrom:
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret
        - configMapRef:
            name: env-configmap
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m